### ISSUE TITLE
ntex.rs is down

### ISSUE THREAD

**Issue by fafhrd91** [ntex-rs/website#12]
@leon3s website is down, should we use GitHub for hosting?

**Comment by 0xle0ne** [comment]
The website is working for me ?

**Comment by fafhrd91** [comment]
I see this:

Web server is down Error code 521
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_521&utm_campaign=ntex.rs) for more information.
2024-08-30 14:13:23 UTC
You
Browser
Working
San Jose
[Cloudflare](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_521&utm_campaign=ntex.rs)
Working
ntex.rs
Host
Error

**Comment by 0xle0ne** [comment]
You aren't in https ?

**Comment by fafhrd91** [comment]
I see, could we make redirect ?

**Comment by 0xle0ne** [comment]
I removed the feature because of this article: https://jviide.iki.fi/http-redirects

Let me know what you think about it

**Comment by 0xle0ne** [comment]
I used hsts instead

**Comment by fafhrd91** [comment]
it doesn't matter, ntex.rs is plain text

**Comment by 0xle0ne** [comment]
alright i'll add the redirection

**Comment by fafhrd91** [comment]
interesting, it redirects now. but initially it should error.
in any case, let's add redirect

**Comment by 0xle0ne** [comment]
It's redirect because the browser hit the hsts header, it wont redirect if you open a incognito tab and try again

**Comment by 0xle0ne** [comment]
I have added a redirection

**Comment by fafhrd91** [comment]
thanks

**Comment by ZhenYisp** [comment]
@leon3s 502 again :face_holding_back_tears:

**Comment by 0xle0ne** [comment]
Yeah all my services when down during the night.. I'm checking this ASAP..

**Comment by 0xle0ne** [comment]
@LazhiHero fixed.

**Comment by 0xle0ne** [comment]
The problem occurred at my cloud provider level:
https://network.status-ovhcloud.com/incidents/ndkfnxy1ylv4
